### ISSUE TITLE
recursive call in xcodeproject makes the app crash

### ISSUE THREAD

**Issue by arturoc** [openframeworks/projectGenerator#137]
https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L958

that call is somehow being called recursively until it fills the stack and the app crashes. i'm getting it when trying to update the current xcode project for the commandLine tool

**Comment by ofZach** [comment]
hmmm -- maybe something broke in the template.  I think the idea here is that we search for header include paths tag, if it does exist we add this include to that, if it doesn't exist, we add this tag and then call add include again.

**Comment by ofZach** [comment]
ah yeah the template has been converted back from xml to plist in the last change (6 days ago) 

<img width="1275" alt="screen shot 2016-10-19 at 4 30 36 am" src="https://cloud.githubusercontent.com/assets/142897/19511336/df0d4f50-95b4-11e6-8839-d5218f3ba684.png">

it should be converted back to xml (since the PG only works via xml) vis plutil 

http://hints.macworld.com/article.php?story=20050430105126392

**Comment by ofZach** [comment]
to add more detail, we work with the template as xml, and produce a new file via the PG as xml, but when you open the file in xcode it converts it back to plist on the first open, so it's possible to break things if you open the template file project itself directly in xcode.   plutil will convert it back.

**Comment by arturoc** [comment]
ah, yeah i probably edited it from xcode and save it. i'll convert it back, thanks!
