### ISSUE TITLE
Windows: drag and drop error

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/projectGenerator#157]
Hi,
I've noticed an error in windows (win 10, x64)  that it will add an incorrect folder path when you drag and drop a project folder into PG. Right now this folder path includes the folder that one is drag'n'droping but it should be the path of the folder that contains the folder being dragged.
Example.
this is how it shows now:
`OF_folder/apps/myApps/project_folder_being_dragged`
but it should be 
`OF_folder/apps/myApps`

I haven't worked with PG code so I'll have to dig a bit to find how to fix this. Sure it is an easy thing. But I wont be able to do this until a few more days. If anyone knows how to fix it please go for it. :)

All the best!

**Comment by Daandelange** [comment]
Hey Roy,
My guess would be that the RegEx is not working correctly on windows.
Check [`/frontend/app.js` (line 726)](https://github.com/openframeworks/projectGenerator/blob/master/frontend/app.js#L726)
To test, you can open the Webkit inspector in the PG and paste this in the console:
```
var folder = "myGeniusApp";
var fullPath = "/path/to/of/apps/myApps/myGeniusApp";
var regExp2 = new RegExp("\\b/"+folder+"\\b","gi");
fullPath.replace(regExp2,"");
```
Otherwise the problem could be e.originalEvent.
Try changing `var files = e.originalEvent.dataTransfer.files;` to `var files = e.files;`.

Debugging can be done with breakpoints via the Webkit Inspector.

**Comment by roymacdonald** [comment]
Hi @Daandelange Thanks for the tips. I will give it a try and post the results.
Best!

**Comment by hiroMTB** [comment]
I assume this is not fixed yet?

**Comment by roymacdonald** [comment]
@hiroMTB I have no idea. At least I did not fix it.
best

**Comment by hiroMTB** [comment]
@Daandelange 
Your first idea is right.
Windows returns path with forward slash, (e.g. \of\apps\mySketch)
macOS and Linux returns path with back slash (e.g. /of/apps/mySketch)
So RegExp can not find project name on Windows. (This is so so annoying btw!)

I tested path.normalize() with / and it works for both of macOS and Windows.
