### ISSUE TITLE
Visual Studio Template problem (object output overwrites each other)

### ISSUE THREAD

**Issue by bakercp** [openframeworks/projectGenerator#159]
If two files in two addons have the same name, Visual Studio 2015 will result in errors.

Here is an example:

https://github.com/bakercp/ofxJSONRPC/issues/10

We should update the VS2015 template with the correct object output filename as noted in the solution:

`$(IntDir)” to “$(IntDir)/%(RelativeDir)/”`

**Comment by bakercp** [comment]
Fix submitted.

**Comment by DynAikon** [comment]
This results in a folder being generated at the same level as the application level folder called "addons" with addon objects being placed there. Is this expected behavior? eg., I now have: Code/openFrameworks/apps/myApps with a folder called addons in the myApps folder. Same if I compile examples...I end up with an addons folder with .obj files at the examples folder level.

**Comment by arturoc** [comment]
I've reverted the PR related to this issue since it was introducing another more critical one: https://github.com/openframeworks/openFrameworks/issues/6050 and creating the obj files out of the obj folder for addons as pointed out by @DynAikon

**Comment by armadillu** [comment]
some discussion about this in https://github.com/openframeworks/openFrameworks/pull/5655#issuecomment-355404874
