### ISSUE TITLE
ofxEdsdk triggers weird glitch in project generator

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#37]
(copied from https://github.com/openframeworks/openFrameworks/issues/4362 )

if i use the pgElectron to make a new project with ofxEdsdk (the develop branch, which has the proper libs/ofxEdsdk/lib path) then i get an EDSDK.framework added to the copy files phase with this path:

/Users/kyle/Documents/openFrameworks/le/Documents/openFrameworks/addons/ofxEdsdk/libs/EDSDK/lib/EDSDK.framework

which seems to be munging a relative path and an absolute path, with the "le" in the middle probably referring to "kyle/Documents".

other addons seem to work ok though.

**Comment by ofZach** [comment]
can you run this in verbose and post the console log and / or run this from the command line via npm start and past in the full output?  I am not seeing any issues with ofxEdSdk over here.

**Comment by ofZach** [comment]
ah I see the issue, none the less verbose console output is pretty helpful to see where things are getting mangled...

**Comment by ofZach** [comment]
note to self -- take a look at this logic more closely: 

https://github.com/openframeworks/projectGenerator/blame/master/ofxProjectGenerator/src/addons/ofAddon.cpp#L509-L519

**Comment by ofZach** [comment]
the path wonkiness should be fixed now (at least the path problem) 

https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/addons/ofAddon.cpp#L507-L508

one thing I am not sure about is if frameworks also need to be in the siderbar...  at the moment frameworks ar added as a build step, but they appear red since I think they are missing in the sidebar.  When I build an app, the framework is present inside the .app package, so this step is working, but I am worried that if they aren't in the sidebar there may be linking errors?

<img width="1151" alt="screen shot 2015-10-15 at 8 50 58 am" src="https://cloud.githubusercontent.com/assets/142897/10514161/1f3dd284-731a-11e5-9315-1f2822d517da.png">

investigating....

**Comment by ofZach** [comment]
ok fixed this now via https://github.com/openframeworks/projectGenerator/commit/5bef3e080c95d43aca709aa8944a9dd3de395473

I am not 100% sure if local_addons will do this right but for regular addons this should be ok: 

<img width="252" alt="screen shot 2015-10-15 at 9 06 33 am" src="https://cloud.githubusercontent.com/assets/142897/10514514/1d8acda0-731c-11e5-9ad2-46fd19e0cabb.png">

also @kylemcdonald it looks like you have duplicate header files in the develop version of the ofxEdSdk addon (see screenshot).  I thought it was the PG, but it's in the addon itself.

**Comment by kylemcdonald** [comment]
@ofZach i don't see the multiple headers you're talking about:

https://github.com/kylemcdonald/ofxEdsdk/tree/develop/libs/EDSDK

i only see the "include" folder.

that said, it is a mistake that the headers are in the repo at all. they come with EDSDK and should be copied over manually.

**Comment by ofZach** [comment]
Ah not sure what that is then.  Anyway more importantly this problem is fixed please test.

**Comment by ofZach** [comment]
closing this as I'm pretty sure this is fixed by now.  feel free to reopen.
