### ISSUE TITLE
always report project generator string that's used in the console output

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#42]
it's really useful to see the command line string that we are using in the console output so we can go test it by hand if need be, ie the "projectGenerator -o="....." -r ......"  string.    I think that used to be in there at some point.

**Comment by Daandelange** [comment]
yes it was in the console, looks like it's been stripped out. Shall I put that back ?

**Comment by ofZach** [comment]
yeah I think it's a good idea to put it back in, so we can debug easier any problems.

**Comment by Daandelange** [comment]
There you go, with a readme entry and I also put back my last forgotten commit from ofZach/pgElectron

**Comment by ofZach** [comment]
thanks !   I don't think we need it in an ever present console -- just to be reported on the console you see with success / failure dialog...

**Comment by Daandelange** [comment]
It's pretty discreet like this and I find it useful useful to trace back generated projects and, as you said, look at their command line string. What about simplifying/shortening it so that you only see the command history, clicking on each of them them will show their console output.

The verbose mode setting already defines if we see the success modal with a console (btw, this setting does nothing for the moment... and is not present in the default `settings.json`)

So I see the verbose option more as a project related setting while the showConsole setting is related to all projects.

**Comment by ofZach** [comment]
no I'm sorry we already decided not to have this console.  we already have 3 potential console outputs

a) the console output if you run electron from the command line (ie npm start) 
b) the console output if you run developer tools
c) the console output from success / failure on generate project. 

I really don't think we need a 4th and I think this just confuses things to have this user facing.  all I am asking for here is to always put the command line string that we are firing off the command line tool in the console output of (c).    We could improve the reporting in (a / b) if it feels like we need to give better feedback.   thanks!

**Comment by ofZach** [comment]
(ps this is where we decided not to have this additional console https://github.com/ofZach/pgElectron/issues/24#issuecomment-134220973)

**Comment by Daandelange** [comment]
Ok, that sounds good! Sorry for the confusion...
In fact i saw the showConsole as a hidden setting but by cleaning up the other consoles it's enough too. :+1: 

I added some commits removing the old console code and adding support for verbose option.

**Comment by ofZach** [comment]
I've added this now -- closing this issue
