### ISSUE TITLE
zsh: killed if OF uses download_latest_libs.sh

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#539]
I'm compiling the latest projectGenerator using make and it compiles both with classic libs and latest.
but when I run using the latest libs I got 
```
zsh: killed
```

**Comment by danoli3** [comment]
Yeah its gotta be signed run it through the script 

We can make this accept a code signing identity:
build_cmdline.sh

or just run the output Xcode project and build it locally that way it will sign for you. 
Else it will be signed via GitHub release

**Comment by danoli3** [comment]
Wait I think I read that in inverse

**Comment by danoli3** [comment]
Yeah Nah its looking working from latest... (osx)
<img width="705" alt="Screenshot 2024-07-11 at 4 04 45 AM" src="https://github.com/openframeworks/projectGenerator/assets/830748/797c2e7e-40c5-4b94-b796-2ef7d3308af9">

what happens when you run it via the command (double click ) - activates console output:
<img width="855" alt="Screenshot 2024-07-11 at 4 05 20 AM" src="https://github.com/openframeworks/projectGenerator/assets/830748/9cdfba67-6618-4575-a0e3-e89dbe3b5016">

**Comment by danoli3** [comment]
I think its due to Debug Mode on default build, try release

**Comment by danoli3** [comment]
I think its actually macOS target folders should be fixed with permissions and or chmod

**Comment by dimitre** [comment]
from my usage it is always killed if I compile via xcodebuild (first time)
strange thing is if I compile it twice it works well
make works well too.

this xcode project is strange because it uses a very unusual renaming and moving in the end. maybe this is causing the problems

**Comment by danoli3** [comment]
@dimitre it means it not signed and you just gotta run the build script to sign it 
```scripts/osx/build_cmdline.sh```

Issue is macOS permissions now are hectic for unsigned code

**Comment by danoli3** [comment]
Building from Xcode will make the file correctly, but it's linking against the mach-o of the files in the .app: invalidating the cmdLine.exe that is copied out of that .app and into the usable folder. Since before it was signed it had references to all that .app stuff. Re-signing in the new location with the script fixes it

**Comment by danoli3** [comment]
not a libs problem, was a new macOS permissions problem

**Comment by danoli3** [comment]
> it would be great if PG could be built in the future only as a commandLine application instead of an app bundle.

scripts/osx/build_cmdline.sh
