### ISSUE TITLE
Windows X64 issue

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/projectGenerator#95]
it seems to me the new projectGenerator can't include proper x64 link library files,i.e the ofxopencv while switching to 64 bit,they were blank in Linker Options.
![Uploading pg1.png…]()
sorry,can't upload any attached files.

**Comment by mattfelsen** [comment]
I just tried this and it looked good to me. Are you trying with 0.9.0 or the latest from `master`?

**Comment by ofZach** [comment]
also it would be good if you can provide two files (or the diff) to compare: 

(a) what the PG generated 
(b) what the project should have to compile

**Comment by liquidzym** [comment]
sorry for the confusing,i'm using the pg from 0.9.0 not from the latest branch
and the default ofxopencv working good with new PG tool,both 32&64 got proper links
but i was built opencv myself with opencv version 2.4.11,that didn't work with PG(only the x64 not working)

the default one working 
![pg2](https://cloud.githubusercontent.com/assets/51957/11436963/8a97597a-9524-11e5-95c2-a754ab9af862.png)

my ofxopencv2 not working
![opencv2](https://cloud.githubusercontent.com/assets/51957/11436960/83bd2ff8-9524-11e5-9a92-d85eff4d28e8.png)

![opencv](https://cloud.githubusercontent.com/assets/51957/11436859/a4c6c976-9523-11e5-8e32-b6e186f62a74.png)

**Comment by mattfelsen** [comment]
Ahh I see why, this is very silly :smile: Looks like the project generator is doing a case-sensitive check on folder names. Can you try renaming your folder to x64 (instead of X64) and try again?

Also, you no longer need to have the last letter of the filename be "d" for debug libs. Instead the pg will look at the folder structure to try and figure out which libs are 32/64 for debug/release. 

The original discussion is here https://github.com/openframeworks/openFrameworks/issues/4241

**Comment by mattfelsen** [comment]
For reference the definitions are here https://github.com/openframeworks/projectGenerator/blob/64c76243690e3b99ad8f09e8abeb0ad2feb7ac96/ofxProjectGenerator/src/utils/LibraryBinary.cpp#L3-L4

**Comment by liquidzym** [comment]
@mattfelsen ,thxs for the help,didn't notice this, it's working after i renamed it to x64
cheers
